### ISSUE TITLE
[BUG] In Chrome delete button hide after reopen select

### ISSUE THREAD

**Issue by cappster** [bithost-gmbh/ngx-mat-select-search#133]
In latest version of Google Chrome (73.0.3683.86) delete button hide after reopen select. [Video](https://youtu.be/K3pVXiC_opM)

**To Reproduce**
1. Set `[clearSearchInput]=false`
2. Click on select
3. Type some search query
4. Close select
5. Click on select

**Comment by macjohnny** [comment]
thanks for reporting. seems to be due to the animation
https://github.com/bithost-gmbh/ngx-mat-select-search/blob/0f675b55d36c0935813b3e53a15e0a29feee8b04/src/app/mat-select-search/mat-select-search.component.ts#L119-L128
<img width="927" alt="Bildschirmfoto 2019-03-28 um 14 54 04" src="https://user-images.githubusercontent.com/5589029/55163059-61753d00-5169-11e9-8ad4-a340673b6f73.png">

**Comment by macjohnny** [comment]
this is fixed in version `1.7.1`
