### ISSUE TITLE
[Question] load the initial bank list with BehaviorSubject instead of ReplaySubject

### ISSUE THREAD

**Issue by StSenf** [bithost-gmbh/ngx-mat-select-search#152]
Hi!

Thank you for your awesome work, it is awesome! 

I was wondering if you could replace the ReplaySubject of filteredBanks in your Stackblitz example with a BehaviorSubject.

In your Stackblitz https://stackblitz.com/github/bithost-gmbh/ngx-mat-select-search-example?file=src%2Fapp%2Fexamples%2F01-single-selection-example%2Fsingle-selection-example.component.ts

you have in line 27 a ReplaySubject with bufferSize 1
`
/** list of banks filtered by search keyword */
public filteredBanks: ReplaySubject<Bank[]> = new ReplaySubject<Bank[]>(1);
`

and then in line 42 you do push an initial value to this ReplaySubject
`
ngOnInit() {
    ...
    // load the initial bank list
    this.filteredBanks.next(this.banks.slice());
   ...
}
`

Do you actually mimic the behavior of a BehaviorSubject with this?

I did change it to a BehaviorSubject in the provided Stakblitz to test it, but unfortunatelly no banks are loaded then. Am I on the wrong track here?

Thank you again!

**Comment by macjohnny** [comment]
it is absolutely possible to use a `BehaviorSubject` instead of a `ReplaySubject`, you then just need to make sure that the option to be selected initially is among the initial options of the behavior subject.


E.g. 
```typescript
filteredBanks: BehaviorSubject<Bank[]> = new BehaviorSubject<Bank[]>(BANKS);
```
see https://stackblitz.com/edit/github-rdgm9d?file=src/app/examples/01-single-selection-example/single-selection-example.component.ts

Actually you could even work without subjects / observables at all.

Does that answer your question?

**Comment by StSenf** [comment]
Thanks for your fast reply!

It anwsers half of my question. If you are using now a BehaviorSubject, line 42 of your code is not needed anymore, or? Cause the BehaviorSubject already sending the initial value

` // load the initial bank list`
`this.filteredBanks.next(this.banks.slice());`

**Comment by macjohnny** [comment]
Yes, line 42 is not needed in that case

**Comment by macjohnny** [comment]
closing since the question should be answered.
