### ISSUE TITLE
[BUG] I'm facing a problem if matsearch is in a modal, using bootstrap 4

### ISSUE THREAD

**Issue by francisnadal** [bithost-gmbh/ngx-mat-select-search#234]
**Describe the bug**
We have a modal and I've added a matsearch functionality in it but I'm not able to click the matsearch field and type. I've made a stackblitz but it's even worse here the dropdown is behind the modal. In our app everything is okay except the inability to type in the matsearch field

*Important* Please provide a reproduction example.
https://stackblitz.com/edit/github-xkpv1x-modal-problem

Thanks

**Comment by macjohnny** [comment]
this is due to the fact that you are using a `mat-select` element from the angular material library together with a bootstrap modal dialog. The z-index calculation of overlays is done in each framework separately, leading to an incompatibility.

Closing this as unrelated to `ngx-mat-select-search`, since the issue also occurs without using `ngx-mat-select-search`, see
https://stackblitz.com/edit/github-xkpv1x-modal-problem-lhn4bh?file=src/app/examples/01-single-selection-example/single-selection-example.component.html

**Comment by macjohnny** [comment]
@francisnadal you could try to manually set the z-index of the mat-select overlay

**Comment by julienboulay** [comment]
With bootstrap 5, in order to fix the issue with the inability to type in the matsearch field, the attribute `data-bs-focus="false"` can be set on the bootstrap `modal` element.
