### ISSUE TITLE
[BUG] : Server side search NoEntriesfoundlabel not working fine always.

### ISSUE THREAD

**Issue by Arjun-1r** [bithost-gmbh/ngx-mat-select-search#239]
**Describe the bug**
When we search the dropdown unknown value it is expected to show No search results found for the search as per NoEntriesfoundlabel. But it is not working 100%. 

**To Reproduce**
See it in action at https://stackblitz.com/github/bithost-gmbh/ngx-mat-select-search-example
1. Go to the example
2. On server-side search dropdown type in 'dddddd' some unknown input. 

**Expected behavior**
No results found the label should be displayed.

**Screenshots**
Screenshot not needed. In the example itself, we can see.

**Desktop (please complete the following information):**

 - OS: Windows
 - Browser: Chrome

**Additional context**
Please solve this bug.

**Comment by macjohnny** [comment]
@Arjun-1r thanks for reporting.
I guess this is due to
https://github.com/bithost-gmbh/ngx-mat-select-search/blob/8cf1cf5ca6527b611ae1e0d39fea774d371749f3/src/app/mat-select-search/mat-select-search.component.ts#L343-L349
not being invoked, since no options change when initially typing a keyword that leads to no results
https://github.com/bithost-gmbh/ngx-mat-select-search/blob/8cf1cf5ca6527b611ae1e0d39fea774d371749f3/src/app/mat-select-search/mat-select-search.component.ts#L306-L310
