### ISSUE TITLE
In latest angular and material version placeholderLabel not showing

### ISSUE THREAD

**Issue by aminsmartsenese** [bithost-gmbh/ngx-mat-select-search#256]
"@angular/material": "^10.1.3",
"@angular/cli": "~10.0.6"

If mat-form-field with [floatLabel]="'never'" this property.

**Comment by macjohnny** [comment]
@aminsmartsenese thanks for reporting the issue.
would you like to find a fix?

**Comment by aminsmartsenese** [comment]
> @aminsmartsenese thanks for reporting the issue.
> would you like to find a fix?

Thank you @macjohnny 

Yes looking solution for that.
If mat-form-field with [floatLabel]="'never'" this property on that time issue is coming.

**Comment by martibenn** [comment]
https://github.com/angular/components/issues/20080 
No help from Angular-Material 😐

**Comment by macjohnny** [comment]
the problem is that in
https://github.com/angular/components/blob/1f6b90c0a515397526d7c6b35f047827bfaa8652/src/material/input/input.ts#L369-L374

the `this._formField` is the parent select component, since there is no form field surrounding the `matInput`.

A solution would be to remove the `matInput` directive and ensure that the correct styles are applied.
If anyone is willing to do this, it would be great.
