### ISSUE TITLE
[BUG] Input is cleared if no results are found

### ISSUE THREAD

**Issue by directcuteo** [bithost-gmbh/ngx-mat-select-search#285]
**Describe the bug**
I am using the `ngx-mat-select-search` to add multiple tags to a form. Everything works perfect except one thing: the select-trigger is cleared when there are no options after filtering.

**To Reproduce**
1. Open dropdown
2. Add a tag
3. Search a tag that doesn't match the already added tag
4. Look at the select trigger - it is now cleared (placeholder text is shown). In order to see this, the select overlay has to be below the select-trigger and not over it like it comes by default.

The issue can be seen on the stackblitz page of the library if the overlay is moved from dev-tools by adding enough `top` value.

**Expected behavior**
The already selected tags should remain visible in the select-trigger when searching. This should have nothing to do with the search.

**Desktop:**

OS: windows 10, x64
Browser: Chrome 87.0.4280.66

**Additional context**

I know that this problem has already been discussed in other threads but not specifically.
As I can see, angular material is doing some things behind and it's completely removing the mat-select-trigger from the dom when the search doesn't match any value.

I even use the value from the form, which still has the already selected value in it on step 4, but the select trigger still gets removed:
        `<mat-select-trigger>{{ formGroup.get('tags').value }}</mat-select-trigger>`

I'm not sure where the problem is but this is definetly not working as I would expect.

I ask for guidance and thank you!

**Comment by macjohnny** [comment]
hi
the origin of this issue is found in the `mat-select` component, since the currently selected value needs to be among the currently available options. if you use `ngx-mat-select-search`, the options not matching the search input will be temporarily removed, resulting in the `mat-select` showing the placeholder instead of the trigger.

https://github.com/angular/components/blob/34a43f62233790d083f2c0a041fc6740640584cd/src/material/select/select.html#L16-L20

https://github.com/angular/components/blob/34a43f62233790d083f2c0a041fc6740640584cd/src/material/select/select.ts#L793-L795

https://github.com/angular/components/blob/34a43f62233790d083f2c0a041fc6740640584cd/src/cdk/collections/selection-model.ts#L99-L101

I think this is a limitation of how `ngx-mat-select-search` is intended to be used, since it would be much easier if `mat-select` had an API to visually hide but not remove an option.

nevertheless, you could achieve the desired behavior by creating a dummy `mat-option` element with a special value and temporarily select it, while making sure it is correctly deselected when the search is reset etc.

**Comment by macjohnny** [comment]
you could also just ensure the currently selected option is never filtered out from the result, and visually hide it if needed.

**Comment by directcuteo** [comment]
Thank you for the suggestions. I've manage to achieve what I wanted with your tips 👍
