### ISSUE TITLE
Bug in IE11: Styling broken and select not useable in automation scenarios

### ISSUE THREAD

**Issue by Sabartius** [bithost-gmbh/ngx-mat-select-search#29]
Hi,

in Internet Explorer 11 the styling of the component is broken. It breaks out of the Overlay and there is no Placeholder inside the input.
![grafik](https://user-images.githubusercontent.com/12798114/40601112-1597a8f0-6254-11e8-893c-e5eedbd31019.png)

Furthermore the component is not useable when automating the application with tools like protractor.
Protractor tries to "scrollIntoView" the specific Option it wants to click onto, but in this case it scrolls right under the search-input, so that it is not clickable.

**Comment by macjohnny** [comment]
@Sabartius thanks for reporting the issue!
> in Internet Explorer 11 the styling of the component is broken. It breaks out of the Overlay and there is no Placeholder inside the input.

Unfortunately, I am not able to reproduce your IE11 width issue. This is what I get with IE11:
![ie](https://user-images.githubusercontent.com/5589029/40602295-592b78d6-6258-11e8-9b21-9049a12943bb.png)
Could you provide more details how you used the component?
However, the placeholder is missing, as you reported. Would you like to give it a try and implement a fix?

> Furthermore the component is not useable when automating the application with tools like protractor.
Protractor tries to "scrollIntoView" the specific Option it wants to click onto, but in this case it scrolls right under the search-input, so that it is not clickable.

I don't yet know how this problem arises, since the search field correctly takes up the space needed and shifts the options down. Could you create a dummy html / css demonstrating the problem?

**Comment by Sabartius** [comment]
I reproduced it: https://stackblitz.com/edit/github-kygcsp?file=src%2Fapp%2Fapp.component.ts

The Select-Panel has a hard max-width of 280px. If an MatOption has a longer text, the search Input seems to grow further, than this maximum.

When you open the Panel it should automatically scroll to Bank K (Italy), but because the Input overlays it, you can't see it

**Comment by macjohnny** [comment]
@Sabartius thanks for the example showing the issue.
Indeed, now I can also reproduce the width-issue in IE. I think this is related to the code in https://github.com/bithost-gmbh/ngx-mat-select-search/blob/master/src/app/mat-select-search/mat-select-search.component.ts#L375-L398

Could you please help me and find a solution for it?

Could you also propose a solution to the automation issue?

**Comment by macjohnny** [comment]
@Sabartius could you please open a separate issue concerning the automation part? I think we can find a way to achieve this without changing the layout.

**Comment by macjohnny** [comment]
@Sabartius would you mind stating the automation case in a separate issue? I guess this could be solved with test-specific css styles.

**Comment by Sabartius** [comment]
@macjohnny test-specific css styles are not an option in my opinion, especially not in an end2end scenario. But i solved it in a more pragmatic way: by filtering for the option i need, so that there is no scrolling inside the select necessary.
