### ISSUE TITLE
load more on scroll (Infinite scroll) 

### ISSUE THREAD

**Issue by irowbin** [bithost-gmbh/ngx-mat-select-search#37]
Is it possible to add infinite scroll to load more record from server? I think this feature isn't implemented yet.

**Comment by macjohnny** [comment]
@irowbin sounds like a good idea! 
currently, you would have to add an scroll event listener to the option container and update the observable feeding the option list. but I guess it is quite some work to get this right.

This feature would be even better in combination with virtual scroll, see https://github.com/angular/material2/issues/823

anyway, unless you think I am wrong, I suggest you to move this to the official repo of material, i.e. create a new issue [here](https://github.com/angular/material2/issues), since this would be a general feature of `MatSelect` rather than `ngx-mat-select-search`
However, if you feel like providing and implementation of this, I would also be ready to include this as part of the `ngx-mat-select-search` library.

How do you want to proceed?

**Comment by macjohnny** [comment]
there exists the following `MatSelect` feature request: https://github.com/angular/material2/issues/11578

@irowbin if you feel like implementing this in `ngx-mat-select-search`, feel free to open another issue and a PR.
