### ISSUE TITLE
Demo broken

### ISSUE THREAD

**Issue by wokier** [bithost-gmbh/ngx-mat-select-search#371]
Hi
Online Demo at stackblitz is broken since yesterday's commit.

**Comment by macjohnny** [comment]
thanks for reporting!

it is strange, locally 
```
git clone https://github.com/bithost-gmbh/ngx-mat-select-search-example.git
npm install
ng serve
````
works fine, and the demo app can be started

any ideas?

**Comment by macjohnny** [comment]
Filed this bug at stackblitz: https://github.com/stackblitz/core/issues/1831

**Comment by wokier** [comment]
The strange thing is that there is code examples in both repositories

https://github.com/bithost-gmbh/ngx-mat-select-search
and
https://github.com/bithost-gmbh/ngx-mat-select-search-example

and they gives different results using stackblitz
https://stackblitz.com/github/bithost-gmbh/ngx-mat-select-search?file=src%2Fapp%2Fapp.component.html
(Error in src/styles.scss (2:9)
NoSuchMethodError: method not found: 'source' on null
╷
2 │ @import "@angular/material/prebuilt-themes/deeppurple-amber";
│ ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
╵
../~/src/styles.scss 2:9 root stylesheet)
https://stackblitz.com/github/bithost-gmbh/ngx-mat-select-search-example?file=src%2Fapp%2Fapp.component.html
(The dependencies for this project couldn't be resolved.)
(this one is used in README documentation)

This is confusing, i have recently made a pull request, and i have modified the examples in the main project only.

**Comment by wokier** [comment]
Please have a look

**Comment by macjohnny** [comment]
Sorry, was on holiday, will try to do it this week

**Comment by macjohnny** [comment]
seems to be working again

**Comment by macjohnny** [comment]
> But the main project exemples is still ko

what do you mean by that? opening https://stackblitz.com/github/bithost-gmbh/ngx-mat-select-search does not work. I don't think this has ever worked, because it somehow does not read the package.json file (you can test older versions e.g. with https://stackblitz.com/github/bithost-gmbh/ngx-mat-select-search/tree/4.0.0).

> Would you mind having the exemples at a single place (ie not duplicated) ?

The reason for having a separate [app/repo](https://github.com/bithost-gmbh/ngx-mat-select-search-example) for the examples is that

- deployment is easier (can be simply done by using stackblitz)
- packaging can be tested correctly

however, I am open to using a different method for deployment, and keeping all the sampels in https://github.com/bithost-gmbh/ngx-mat-select-search only. But I will need to find some time to do that.

**Comment by wokier** [comment]
I am ok with having a separate project for the exemple, but my 2 cents advice is to have them only there, and a dev guide note that mention them. This way contributors would update the exemples only one time, at the correct place. (having 2 pull request at the same time)
