### ISSUE TITLE
It happens again. With v.4.1.1 and Angular Material v.12 :(

### ISSUE THREAD

**Issue by macjohnny** [bithost-gmbh/ngx-mat-select-search#374]
It happens again. With v.4.1.1 and Angular Material v.12 :(

_Originally posted by @Lertis in https://github.com/bithost-gmbh/ngx-mat-select-search/issues/321#issuecomment-1114798942_

**Comment by macjohnny** [comment]
@gkgeorgiev do you want to investigate/fix this?

**Comment by gkgeorgiev** [comment]
@macjohnny  actually I did investigate it and the problem was that an older version (2.1.1) was bundled as a part of my own angular library, and even if my host application was referring to a fixed NGX-... version, Angular was still trying to compile the old javascript as well. 
In other words - my library was bundling within itself, it was looking something like this project_root/node_modules/my_library/node_modules/ngx-mat-select-search

**Comment by macjohnny** [comment]
Oh, I see, so we can close the issue then?

**Comment by gkgeorgiev** [comment]
> 

I would say so, at least in my case it should be working. I'm still coding, but at least it compiles now.
I'm not sure about your case though - if you have sorted it out then yes, we could close the ticket. 

P.S. I see that you are also based in Zurich - World is small :)
