### ISSUE TITLE
Select initial value where only Id is used in the form

### ISSUE THREAD

**Issue by MaticDiba** [bithost-gmbh/ngx-mat-select-search#384]
Hi,
is it possible to set initial value for search control, where `entity.name` should be displayed, and `entity.id` should be used as a form value.

This is an example of my control used in reactive forms:
```html
<div [formGroup]="form">
  <mat-form-field class="inherit-display">
    <mat-select formControlName="entityId"
      placeholder="placeholder" >
      <mat-option>
        <ngx-mat-select-search placeholderLabel="label"
          noEntriesFoundLabel="'noresults'" [formControl]="entitiessSearchCtrl"
          [searching]="searching"></ngx-mat-select-search>
      </mat-option>
      <mat-option>{{ 'None' | translate }}</mat-option>
      <mat-option *ngFor="let entity of filteredEntities | async" [value]="entity.id">
        {{entity.name}}
      </mat-option>
    </mat-select>
  </mat-form-field>
</div>
```
So reactive form group is passed to this component, and the field I want to populate is `entityId`. If I use approach from this example: [https://stackblitz.com/github/bithost-gmbh/ngx-mat-select-search-example](https://stackblitz.com/github/bithost-gmbh/ngx-mat-select-search-example?file=src%2Fapp%2Fapp.component.html) `entityId` is set, but the value in the control is blank.

**Comment by macjohnny** [comment]
You should be able to set it with

https://github.com/bithost-gmbh/ngx-mat-select-search/blob/092aaf963d2b9cb3cb36f79cab1f6d3c6f35aa63/src/app/examples/01-single-selection-example/single-selection-example.component.ts#L64

the comparewith function can simply be

  (a, b) => a === b

this initialization is necessary since the options are asynchronously set

does this help?

If not, please paste the typescript code of your component

**Comment by MaticDiba** [comment]
Yes, this worked. Thanks. Also another problem was, I was trying to set this in onInit method.
