### ISSUE TITLE
[FEATURE] Add pagination if there are too many options. example if I have 1000 items there will be performance issues ignoring the backend factor

### ISSUE THREAD

**Issue by tu-hai** [bithost-gmbh/ngx-mat-select-search#444]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by macjohnny** [comment]
@tu-hai do you want to propose a solution? there are also other approaches, such as virtual scrolling, see e.g. https://github.com/bithost-gmbh/ngx-mat-select-search/issues/304

the tricky part is that the material select expects the selected option to always be present in order to display the value, which could be somehow achieved with a visually hidden option.

**Comment by macjohnny** [comment]
closing this bug as a duplicate of https://github.com/bithost-gmbh/ngx-mat-select-search/issues/423
