### ISSUE TITLE
[BUG] Weird behavior -  Transparency on the search input field 

### ISSUE THREAD

**Issue by JMCelesti** [bithost-gmbh/ngx-mat-select-search#470]
**Describe the bug**
Hello, I found an issue in the last version of ngx-mat-select 
now when you scroll for the available results, it overflows the search input field. It seems there is no more background on this input field.

**To Reproduce**

1. Go to https://bithost-gmbh.github.io/ngx-mat-select-search/
2. Open a select 
3. Scroll down 

Actually it's not visible on https://stackblitz.com/github/bithost-gmbh/ngx-mat-select-search-example 

**Desktop (please complete the following information):**

 - OS: Windows
 - Browser: Chrome
 
 
 Thanks

**Comment by macjohnny** [comment]
thanks for pointing this out! this is because of the build using an older material version, where there is this transparency bug with the latest version of ngx-mat-select-search. closing this for now, since we will just upgrade the angular version of this repo at some point, then the problem should be gone.
