### ISSUE TITLE
Bug with special characters.

### ISSUE THREAD

**Issue by teoCasasbuenas** [bithost-gmbh/ngx-mat-select-search#49]
I just found that the search fields has a bug when using special characters. If you type in an special character, like 'é' it shows the 'noEntriesFoundLabel'. At first it looks like the input got blocked, and for some reason if you try to delete with the "backspace" key (keyCode === 8) at this point, it triggers the history.back() action of the browser.

**Comment by macjohnny** [comment]
@teoCasasbuenas thanks for opening this issue here. I can't reproduce the bug you report. If in https://stackblitz.com/edit/github-orcyls?file=src%2Fapp%2Fapp.component.ts you type `mét` it will correctly find the entry `Bank Gamét (Italy)`. Also, it does not seem to trigger `history.back()`.

Could you please provide an example demonstrating your issue starting with this template: https://stackblitz.com/github/bithost-gmbh/ngx-mat-select-search

I guess there is an issue with your filter function, i.e. your implementation of https://github.com/bithost-gmbh/ngx-mat-select-search/blob/master/src/app/app.component.ts#L119-L135
Could you please post the code snippet of your filter function?

**Comment by teoCasasbuenas** [comment]
@macjohnny I was using the first implementation of the input that you shared in the material thread, and I had not changed to the branch I was developing with the ngx, and I had not noticed. Sorry for wasting your time, my bad, and again thanks for the development of this important element.

**Comment by macjohnny** [comment]
@teoCasasbuenas glad everything works fine. I hope you installed the package via `npm install ngx-mat-select-search` to be able to get improvements developed here.
If you find any other problem or have a suggestino, feel free to open an issue or file a pull request.

**Comment by macjohnny** [comment]
@teoCasasbuenas if you like the project, feel free to star it.
