### ISSUE TITLE
Avoid logic over ViewChild selector

### ISSUE THREAD

**Issue by tsiegleauq** [bithost-gmbh/ngx-mat-select-search#57]
`mat-select [formControl]="bankCtrl" placeholder="Bank" #singleSelect`

ngx-mat-select-search depends on having either the ViewChild named `#singleSelect` or `#multiSelect`.
This prohibits us to change the selection style using a variable.
Forcing the `ViewChild`'s name to be `#singleSelect` or `#multiSelect` should be avoided. 

Rather use `multiple="true"` as in `@input field` or something similar.

See also:
https://material.angular.io/components/select/overview#multiple-selection

**Comment by macjohnny** [comment]
@tsiegleauq you are referring to the example code https://github.com/bithost-gmbh/ngx-mat-select-search/blob/master/src/app/app.component.html#L17-L22
The actual code https://github.com/bithost-gmbh/ngx-mat-select-search/blob/master/src/app/mat-select-search/mat-select-search.component.ts does not have this reference.
The example code simply illustrates how you *can* use the `<ngx-mat-select-search>` component, while it is possible to use it without the `#singleSelect` template reference. 
Or am I missing anything? What would be the code changes you propose?

**Comment by macjohnny** [comment]
@jsaalfeld thanks for your reply. 
The `<ngx-mat-select-search>` should not have any effects on anything except its enclosing `<mat-select>` element. I would also recommend you to use different `[formControl]` inputs in order not to share the same form control, potentially leading to effects.
Since you are reporting that it works in a minimal setup, I close this issue. Feel free to open another issue if you find  anything else that should be improved / fixed.

**Comment by macjohnny** [comment]
@jsaalfeld if you like the project, feel free to star it ;-)

**Comment by tsiegleauq** [comment]
yep we were definitely using it wrong ;-)
thanks for the quick answer and this project
