### ISSUE TITLE
Multi select filtering removes previously selected values

### ISSUE THREAD

**Issue by joqkey** [bithost-gmbh/ngx-mat-select-search#6]
If initially I have all values selected for multi select and then I filter and after that deselect a value, then previously selected values are removed again.

An example is shown here: https://stackblitz.com/edit/github-g1zbuf?embed=1&file=src/app/app.component.html
How to reproduce: Open multi select, type 'France', deselect one option (for example Bank C (France)) - the result is that all other previously selected values are removed.

**Comment by macjohnny** [comment]
the problem is that for multiple-selects, `this.previousSelectedValues` is filled with selected values that are restored when the filtering is reset. `this.previousSelectedValues` is filled whenever `this.matSelect.valueChange` occurs, see https://github.com/bithost-gmbh/ngx-mat-select-search/blob/master/src/app/mat-select-search/mat-select-search.component.ts#L324

The solution would be to initialize `this.previousSelectedValues` once the first filtering occurs.
@joqkey would you like to try to implement a fix by initializing `this.previousSelectedValues`? This could be done by calling a method in https://github.com/bithost-gmbh/ngx-mat-select-search/blob/master/src/app/mat-select-search/mat-select-search.component.ts#L242
