### ISSUE TITLE
Example with Dynamically created FormGroup, specially when the select is inside FormArray

### ISSUE THREAD

**Issue by majoraze** [bithost-gmbh/ngx-mat-select-search#65]
Provide a example using Form Array.

I tried the following with no success:
```
<ng-container *ngFor="let rule of rules; let i = index">
  <td>
    <ng-container formArrayName="rules">
      <mat-form-field>
        <mat-select [formControlName]="i" [compareWith]="compare">
          <ngx-mat-select-search [formControlName]="'SelectSearch'+i"></ngx-mat-select-search>
          <mat-option *ngFor="let option of rule.options" [value]="option">{{option.name}}</mat-option>
        </mat-select>
      </mat-form-field>
    </ng-container>
  </td>
</ng-container>
```

The error says:
Cannot find control with path: 'rules -> SelectSearch0'

**Comment by maechler** [comment]
@majoraze Thanks for your suggestion. If you succeed to implement this it would be nice if you could provide that example!

**Comment by macjohnny** [comment]
@majoraze in your example you are using the wrong form control name `SelectSearch0`. instead, you should use `0` without any string prefix, since the `FormArray` elements are indexed by their integer index.
So you would have
```html
<ngx-mat-select-search [formControlName]="i"></ngx-mat-select-search>
```
and
in the component code you can access e.g. the first filter input with
```typescript
  /** control for the MatSelect filter keyword */
  get bankFilterCtrl(): FormControl {
    return this.myGroup.get('rules.0');
  }
```
See this working example:
https://stackblitz.com/edit/github-nee1is?file=src%2Fapp%2Fapp.component.ts

Since this is not an issue related to `ngx-mat-select-search` but rather a question of how to use the angular form controls, I am closing the issue.

**Comment by ankit-saiyan** [comment]
@macjohnny 
Your implementation is affecting the select element of each row of a form array.

**Comment by macjohnny** [comment]
@ankit-saiyan can you please open a new issue and describe the problem in detail, with a code example?
