### ISSUE TITLE
Compatibility with Angular 7

### ISSUE THREAD

**Issue by RhinojosaDeveloper** [bithost-gmbh/ngx-mat-select-search#71]
Package "ngx-mat-select-search" has an incompatible peer dependency to "@angular/cdk" (requires "^5.0.0 || ^6.0.0", would install "7.0.1").

**Comment by maechler** [comment]
Thanks for reporting, there seems to already be an issue on this for `ngx-webstorage`:
https://github.com/PillowPillow/ng2-webstorage/issues/94

**Comment by macjohnny** [comment]
since version `1.4.0` the dependencies allow angular 7, see https://github.com/bithost-gmbh/ngx-mat-select-search/releases/tag/1.4.0 and 
https://github.com/bithost-gmbh/ngx-mat-select-search/blob/master/package.json#L36-L38
so I close this issue.
@RhinojosaDeveloper or is there any other problem that I did not consider?
